### ISSUE TITLE
When generating a retrofit client is ignoring the first queryParam

### ISSUE THREAD

**Issue by atomsfat** [gextech/raml2code#4]
```yaml
displayName: Login
get:
  queryParameters:
    password:
      type: string
    username:
      type: string
    clientId:
      type: string
    clientSecret:
      type: string
```

It's generating this

```java
  @GET("/v1/login")
  Observable<LoginSuccessJson> getLoginAndClientSecretAndClientIdAndUsername(
    @Query("clientSecret") String clientSecret,
    @Query("clientId") String clientId,
    @Query("username") String username);

  @GET("/v1/login")
  Observable<LoginSuccessJson> getLoginAndClientIdAndUsername(
    @Query("clientId") String clientId,
    @Query("username") String username);

  @GET("/v1/login")
  Observable<LoginSuccessJson> getLoginAndClientSecretAndUsername(
    @Query("clientSecret") String clientSecret,
    @Query("username") String username);

  @GET("/v1/login")
  Observable<LoginSuccessJson> getLoginAndUsername(
    @Query("username") String username);

  @GET("/v1/login")
  Observable<LoginSuccessJson> getLoginAndClientSecretAndClientId(
    @Query("clientSecret") String clientSecret,
    @Query("clientId") String clientId);

  @GET("/v1/login")
  Observable<LoginSuccessJson> getLoginAndClientId(
    @Query("clientId") String clientId);

  @GET("/v1/login")
  Observable<LoginSuccessJson> getLoginAndClientSecret(
    @Query("clientSecret") String clientSecret);

  @GET("/v1/login")
  Observable<LoginSuccessJson> getLogin();
```
The password parameter is misssing, this was reported by @hgmiguel
